### ISSUE TITLE
Does SparsePointStorage need a lock to protect the data from accessing by multiple threads?

### ISSUE THREAD

**Issue by hzeng-tfs** [NModbus/NModbus.v4#22]
```
public class SparsePointStorage<T> : IPointStorage<T>
    {
        private readonly Dictionary<ushort, T> values = new Dictionary<ushort, T>();

        public T this[ushort address] 
        { 
            get
            {
                values.TryGetValue(address, out var value);

                return value;
            }
            set
            {
                values[address] = value;
            }
        }
```
I am not sure if I missed something obvious. I think a lock should be used to protect `values` from accessing by multiple threads. I can see there are at least 2 threads for a Modbus Server:
- an incoming Modbus connection is handled by a thread, 
- another thread which is responsible to update the background values from data sources (e.g. sensors, etc.) periodically

The [V3 of NModbus](https://github.com/NModbus/NModbus/blob/13a454bdc8dd4b5c0399090a5544927235046a65/NModbus/Data/PointSource.cs#L49) uses a lock
```
        public void WritePoints(ushort startAddress, T[] points)
        {
            lock (_syncRoot)
            {
                for (ushort index = 0; index < points.Length; index++)
                {
                    _points.Value[startAddress + index] = points[index];
                }
            }
        }
```

from [here](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0&devlangs=csharp&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(System.Collections.Generic.Dictionary%25602)%3Bk(DevLang-csharp)%26rd%3Dtrue#thread-safety): 
> A [Dictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0) can support multiple readers concurrently, as long as the collection is not modified. Even so, enumerating through a collection is intrinsically not a thread-safe procedure. In the rare case where an enumeration contends with write accesses, the collection must be locked during the entire enumeration. To allow the collection to be accessed by multiple threads for reading and writing, you must implement your own synchronization.
> 
For thread-safe alternatives, see the [ConcurrentDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-8.0) class or [ImmutableDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2?view=net-8.0) class.

Using `Dictionary<ushort, T>` seems not enough. 

Is my understanding correct? Thanks.

**Comment by rquackenbush** [comment]
That is an excellent point. When I wrote this, I had serial RTU in mind,
which is inherently single threaded. In TCP or UDP mode, that’s not the
case and I can envision a race condition occurring under the right
circumstances.

I’m familiar with ConcurrentDictionary and will take a look at migrating to
that instead.

**Comment by rquackenbush** [comment]
Fixed with https://github.com/NModbus/NModbus.v4/pull/26 (using `ConcurrentDictionary`)
